dist: xenial
services:
  - docker
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8-dev'

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.8-dev

stages:
  - lint
  - test
  - deploy

before_install:
  - pip install --upgrade pipenv
  # Numpy isn't needed by pytest-localstack, but it comes preinstalled in Travis.
  # `pipenv check` complains if numpy<=1.16.0.
  - pip install 'numpy>1.16.0'
  - pipenv --version

install:
  # Do this instead of `make env` so we always test with latest versions
  # of packages.
  - pipenv install --dev --pre codecov pytest-cov pytest-xdist

script:
  - pytest --version
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc -k "tests/unit" -n auto
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc --cov-append -k "tests/integration" -n auto
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc --cov-append -k "tests/functional"

after_success:
  - codecov

jobs:
  include:
    - stage: lint
      python: 3.6
      services: []
      install: make env
      script:
        - make lint
        - make docs
      after_success: []
      deploy: []

    - stage: deploy
      if: tag =~ ^v
      python: '3.7'
      services: []
      before_install: []
      install: []
      script: 'true'
      after_success: []
      deploy:
        provider: pypi
        user: jdoepke_mintel
        password:
          secure: fMzAGIp0OJQI5GdeiN0u6g2uTUvlHmGskWfvvaNF+xM4/J3o33LWqyRjRa7m07Mv+2XtuUaFyh5s/wcHlro4Ianx7c3hRa6gx+MxB4akgj8H0xgFrKduZfOcruNGcz0qOwk9PsYSk+KBdfESy0SHotoOZdYT4rB3i12PJgCrO3Dn466qbeNYdWEO+1nZMkGjkGPmGTgann9d2HbRZP1Eu/0ehIU02Gvs0uPzNpq2UBtE6XpAPu7O/yq7l02m21hj1GuMJq86wNHkVi9LGvSvDBIF+iZSvrRSM6/+DYzCq5UKnQy1gPHUVWkZXWcuDrJW5ODZzlG0JHbagLdl4gQKU/0giMHCo9g3f6X7jeFUIAYMKEmwsU6qOO31KiAat7mWMI07peD4SCexQxksVYcUeuriF8A+AkG8qDaeJKdX3wDpOMpi4aWYt2KvIUEyPiHeGruv5y1NIwTQrcpkOxYcZ4/nwrMTph0vvAJsgOCg6NueIQLq2ungeBbXRarg9afU16j5ODWWDNLvJSVE02VgAkKc8Gw7EvtyWRmsr/aV86UXHZ85VImDKvIA1pdJAypa+PjdsVNnfDtcfsDnkROu18dJCBy0tXNuHtsHOjESHrODHBfGh/Wr4/qVO4CQVloB+NIIZNLv9QvbFQV5jfiyLALCIGCw3mujp3y5kJBE2zI=
        distributions: 'sdist bdist_wheel'
        skip_existing: true
        on:
          tags: true
          all_branches: true
