dist: xenial
services:
  - docker
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.8-dev

stages:
  - lint
  - test

before_install:
  - pip install --upgrade pipenv
  - pipenv --version

install:
  # Do this instead of `make env` so we always test with latest versions
  # of packages.
  - pipenv install --skip-lock --dev --pre
  - pipenv run pip install codecov pytest-cov pytest-xdist

script:
  - pytest --version
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc -k "tests/unit" -n auto
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc --cov-append -k "tests/integration" -n auto
  - pytest -ra --cov=pytest_localstack/ --cov-config .coveragerc --cov-append -k "tests/functional"

after_success:
  - codecov

jobs:
  include:
    - stage: lint
      python: 3.6
      services: []
      install: make env
      script:
        - make lint
        - make docs
      after_success: []
